#!/bin/bash

if [ ! -e /usr/bin/prometheus-proxy ]; then
    exit 0
fi

cat << EOF >> /etc/systemd/system/prometheus-proxy.service
[Unit]
Description=OpenStack Octavia Prometheus Proxy
After=network.target syslog.service amphora-agent.service
Requires=amphora-agent.service

[Service]
ExecStart=/usr/bin/prometheus-proxy
KillMode=mixed
Restart=always
ExecStartPost=/bin/sh -c "echo $MAINPID > /var/run/prometheus-proxy.pid"
PIDFile=/var/run/prometheus-proxy.pid

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable prometheus-proxy
