#!/bin/bash

# Workaround for LP: #1831642
chmod 2750 /etc/octavia
sed -i 's/CONFIG_FILE=.*$/CONFIG_FILE=\/etc\/octavia\/amphora-agent.conf/' \
    /etc/init.d/amphora-agent
sed -i '/^User=octavia$/d' /lib/systemd/system/amphora-agent.service
sed -i '/^Group=octavia$/d' /lib/systemd/system/amphora-agent.service

touch /var/log/amphora-agent.log
chmod 0640 /var/log/amphora-agent.log
chown octavia:adm /var/log/amphora-agent.log

cat > /etc/logrotate.d/amphora-agent <<EOF
/var/log/amphora-agent.log {
    create 0640 octavia adm
    daily
    missingok
    compress
    delaycompress
    copytruncate
}
EOF

# Change I30997ae6cc6b8ec724f0e9dcfdfe49356b320ff4 renames
# /usr/local/bin/udp-masquerade.sh to /usr/local/bin/lvs-masquerade.sh
# Let's retain a symlink so that the same Amphora can be used for multiple
# versions.
ln -sf lvs-masquerade.sh /usr/local/bin/udp-masquerade.sh
