#!/bin/bash

# Workaround for LP: #1831642
chmod 2750 /etc/octavia
sed -i 's/CONFIG_FILE=.*$/CONFIG_FILE=\/etc\/octavia\/amphora-agent.conf/' /etc/init.d/amphora-agent

touch /var/log/amphora-agent.log
chmod 0640 /var/log/amphora-agent.log
chown octavia:adm /var/log/amphora-agent.log

cat > /etc/logrotate.d/amphora-agent <<EOF
/var/log/amphora-agent.log {
    create 0640 octavia adm
    daily
    missingok
    compress
    delaycompress
    copytruncate
}
