#!/bin/bash

# The amphora requires the generic kernel to support storing cryptographic
# keys in an encrypted ramfs.
#
# https://github.com/openstack/octavia/tree/master/elements/certs-ramfs
#
# Uninstall the kernel optimized for virtual instances to ensure the generic
# kernel is used.
#
# note that we do this step here both because the uninstall property of
# ``package-installs.yaml`` does not work properly with ``not-arch`` and
# to make sure the generic kernel is the one used for boot.

apt-get remove -y --purge linux-*kvm
apt-get remove -y --purge linux-*virtual
