#!/bin/bash

# note that we do this step here both because the uninstall property of
# ``package-installs.yaml`` does not work properly with ``not-arch`` and
# to make sure the generic kernel is the one used for boot.

sudo apt remove -y --purge "linux-*-kvm"
