#!/bin/bash

# Add the Ubuntu Cloud Archive

apt-get update
apt install ubuntu-cloud-keyring
if [ ! -z "${DIB_UBUNTU_CLOUD_ARCHIVE_MIRROR}" ]; then
    add-apt-repository "$DIB_UBUNTU_CLOUD_ARCHIVE_MIRROR"
elif [ ! -z "${DIB_UBUNTU_CLOUD_ARCHIVE}" ]; then
    add-apt-repository cloud-archive:$DIB_UBUNTU_CLOUD_ARCHIVE
fi
apt-get update
